---
# Cloudera playbook

- name: Configure Cloudera Manager Repository
  hosts: cdh_servers
  roles:
    - role: cm_repo
  tags: cm_repo

- name: Install rngd
  hosts: cdh_servers
  roles:
    - role: rngd
      when: cluster_install_rngd
  tags: rngd

- name: Install Java
  hosts: cdh_servers
  roles:
    - role: java
      when: cluster_install_java 
  tags: java

- name: Install MariaDB and create databases
  hosts: db_server
  roles:
    - role: mariadb
      when: cluster_install_mysql
  tags:
    - mysql
    - mysql_server

- name: Install MySQL Connector
  hosts: cdh_servers
  roles:
    - role: mysql_connector
      when: cluster_install_mysql
  tags:
    - mysql
    - mysql_client

- name: Install MIT KDC Server
  hosts: krb5_server
  roles:
    - role: krb5/server
      when: cluster_install_krb5_server
  tags: krb5

- name: Install MIT KDC Client
  hosts: all
  roles:
    - role: krb5/client
      when: (krb5_kdc_type is defined) and (krb5_kdc_type != 'none')
  tags: krb5

- name: Configure EPEL Repository
  hosts: scm_server
  roles:
    - role: epel
  tags: epel

- name: Install Cloudera Manager Agents
  hosts: cdh_servers
  roles:
    - role: cm_agents
  tags: cm_agents

- name: Install Cloudera Manager Server
  hosts: scm_server
  roles:
    - role: scm
  tags: 
    - cm_server
    - cluster_template

- name: Install CDH
  hosts: scm_server
  roles:
    - role: cdh
      when: cluster_install_cdh
  tags: 
    - cdh
    - cluster_template
