---

# Wait for agents to send heartbeats in case SCM has just been restarted
# Adding CMS will fail if host details haven't been reported in
- name: Wait for agent heartbeats
  pause:
    seconds: 30

- set_fact:
    cms_config_json: "{{ lookup('template', 'cms_base.j2', convert_data=False) }}"

# https://cloudera.github.io/cm_api/apidocs/v12/path__cm_service.html#PUT
- name: Setup the Cloudera Management Services (CMS)
  uri:
    url: "{{ cm_api_url }}/cm/service"
    method: PUT
    body_format: json
    body: "{{ cms_config_json|to_json }}"
    status_code: 200,400
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
  register: cms_resp
  failed_when:
    - "'MGMT' not in cms_resp.content"
    - "'CMS instance already exists' not in cms_resp.content"

- debug: 
    var: cms_resp
    verbosity: 1

# https://cloudera.github.io/cm_api/apidocs/v12/path__cm_service_commands_start.html
- name: Start Cloudera Management Services (CMS)
  uri:
    url: "{{ cm_api_url }}/cm/service/commands/start"
    method: POST
    status_code: 200
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
  register: start_resp
  failed_when: "'startTime' not in start_resp.content"

- debug: 
    var: start_resp
    verbosity: 1
